const fs = require('fs');
const path = require('path');
const https = require('https');

/**
 * CONFIGURATION
 * Provide your Spreadsheet ID here or via environment variable
 */
const SPREADSHEET_ID = process.env.RECIPES_SHEET_ID || '1MtFaLJAr8u96jQ39lbDUGS_M-UDINk08mx6Cmw5yb_Y';
const OUTPUT_FILE = path.join(__dirname, '../src/data/vietnameseRecipes.js');

async function fetchCSV() {
    return new Promise((resolve, reject) => {
        const url = `https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/export?format=csv`;
        https.get(url, (res) => {
            let data = '';
            res.on('data', (chunk) => { data += chunk; });
            res.on('end', () => resolve(data));
        }).on('error', reject);
    });
}

function parseCSV(csvText) {
    const lines = csvText.split('\n');
    const headers = lines[0].split(',').map(h => h.trim());

    return lines.slice(1).map(line => {
        const values = line.split(',');
        const obj = {};
        headers.forEach((header, index) => {
            let val = values[index] ? values[index].trim() : null;

            // Basic type conversion
            if (header === 'ingredients') {
                val = val ? val.split(';').map(i => i.trim()) : [];
            } else if (header === 'readyInMinutes' || header === 'healthScore') {
                val = parseInt(val) || 0;
            } else if (header === 'isLocal') {
                val = val === 'true' || val === 'TRUE';
            }

            obj[header] = val;
        });
        return obj;
    });
}

async function run() {
    console.log('🚀 Starting recipe sync from Google Sheets...');

    if (SPREADSHEET_ID === '1_YOUR_SPREADSHEET_ID_HERE') {
        console.error('❌ Please set RECIPES_SHEET_ID environment variable or update the SPREADSHEET_ID in the script.');
        process.exit(1);
    }

    try {
        const csv = await fetchCSV();
        const recipes = parseCSV(csv);

        if (recipes.length === 0) throw new Error('No recipes found in sheet');

        const content = `// This file is auto-generated by scripts/sync-recipes.js
// Do not edit manually. Last updated: ${new Date().toISOString()}

export const VIETNAMESE_RECIPES = ${JSON.stringify(recipes, null, 4)};
`;

        fs.writeFileSync(OUTPUT_FILE, content);
        console.log(`✅ Success! Synced ${recipes.length} recipes to ${OUTPUT_FILE}`);

    } catch (error) {
        console.error('❌ Sync failed:', error.message);
        process.exit(1);
    }
}

run();
